//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdaaMobile.Strings {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdaaMobile.Strings.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADAA Timesheet.
        /// </summary>
        public static string AdaaTimesheet {
            get {
                return ResourceManager.GetString("AdaaTimesheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Comment.
        /// </summary>
        public static string AdditionalComment {
            get {
                return ResourceManager.GetString("AdditionalComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Comments.
        /// </summary>
        public static string AdditionalComments {
            get {
                return ResourceManager.GetString("AdditionalComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        public static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Announcement.
        /// </summary>
        public static string Announcement {
            get {
                return ResourceManager.GetString("Announcement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANNOUNCEMENT.
        /// </summary>
        public static string AnnouncementCap {
            get {
                return ResourceManager.GetString("AnnouncementCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Announcement Type.
        /// </summary>
        public static string AnnouncementType {
            get {
                return ResourceManager.GetString("AnnouncementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADAA.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عربى.
        /// </summary>
        public static string Arabic {
            get {
                return ResourceManager.GetString("Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance.
        /// </summary>
        public static string Attendance {
            get {
                return ResourceManager.GetString("Attendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance.
        /// </summary>
        public static string AttendanceAndLeave {
            get {
                return ResourceManager.GetString("AttendanceAndLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance.
        /// </summary>
        public static string AttendanceTab {
            get {
                return ResourceManager.GetString("AttendanceTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buisness Card.
        /// </summary>
        public static string BuisnessCard {
            get {
                return ResourceManager.GetString("BuisnessCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card has been saved.
        /// </summary>
        public static string CardSavedMessaga {
            get {
                return ResourceManager.GetString("CardSavedMessaga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate.
        /// </summary>
        public static string Certificate {
            get {
                return ResourceManager.GetString("Certificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Name in Arabic.
        /// </summary>
        public static string CertificateNameInArabic {
            get {
                return ResourceManager.GetString("CertificateNameInArabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Name in English.
        /// </summary>
        public static string CertificateNameInEnglish {
            get {
                return ResourceManager.GetString("CertificateNameInEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language.
        /// </summary>
        public static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change my laptop password.
        /// </summary>
        public static string ChangeLaptopPass {
            get {
                return ResourceManager.GetString("ChangeLaptopPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Greeting Card Type.
        /// </summary>
        public static string ChooseGreetingCardType {
            get {
                return ResourceManager.GetString("ChooseGreetingCardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language.
        /// </summary>
        public static string ChooseLanguage {
            get {
                return ResourceManager.GetString("ChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose office location..
        /// </summary>
        public static string ChooseOfficeLocation {
            get {
                return ResourceManager.GetString("ChooseOfficeLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Pass.
        /// </summary>
        public static string DayPass {
            get {
                return ResourceManager.GetString("DayPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delegate Name.
        /// </summary>
        public static string DelegateName {
            get {
                return ResourceManager.GetString("DelegateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delegation.
        /// </summary>
        public static string Delegation {
            get {
                return ResourceManager.GetString("Delegation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELEGATION DETAILS.
        /// </summary>
        public static string DelegationDetailsCap {
            get {
                return ResourceManager.GetString("DelegationDetailsCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure time.
        /// </summary>
        public static string DepartureTime {
            get {
                return ResourceManager.GetString("DepartureTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deprature Time.
        /// </summary>
        public static string DepratureTime {
            get {
                return ResourceManager.GetString("DepratureTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination.
        /// </summary>
        public static string Destination {
            get {
                return ResourceManager.GetString("Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory.
        /// </summary>
        public static string Directory {
            get {
                return ResourceManager.GetString("Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIRECTORY.
        /// </summary>
        public static string DirectoryCap {
            get {
                return ResourceManager.GetString("DirectoryCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver Request.
        /// </summary>
        public static string DriverRequest {
            get {
                return ResourceManager.GetString("DriverRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Directory.
        /// </summary>
        public static string EmployeeDirectory {
            get {
                return ResourceManager.GetString("EmployeeDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee ID.
        /// </summary>
        public static string EmployeeID {
            get {
                return ResourceManager.GetString("EmployeeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---.
        /// </summary>
        public static string EmptyPlaceHolder {
            get {
                return ResourceManager.GetString("EmptyPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter additional comments..
        /// </summary>
        public static string EnterAdditionalComments {
            get {
                return ResourceManager.GetString("EnterAdditionalComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter service details..
        /// </summary>
        public static string EnterServiceDetails {
            get {
                return ResourceManager.GetString("EnterServiceDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong username or password.
        /// </summary>
        public static string EnterValidPassword {
            get {
                return ResourceManager.GetString("EnterValidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Services.
        /// </summary>
        public static string EServices {
            get {
                return ResourceManager.GetString("EServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceptions.
        /// </summary>
        public static string Exceptions {
            get {
                return ResourceManager.GetString("Exceptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected Return Time.
        /// </summary>
        public static string ExpectedReturnTime {
            get {
                return ResourceManager.GetString("ExpectedReturnTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Location.
        /// </summary>
        public static string FirstLocation {
            get {
                return ResourceManager.GetString("FirstLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Seen.
        /// </summary>
        public static string FirstSeen {
            get {
                return ResourceManager.GetString("FirstSeen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string FlowDirection {
            get {
                return ResourceManager.GetString("FlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget Password.
        /// </summary>
        public static string ForgetPassword {
            get {
                return ResourceManager.GetString("ForgetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greeting Card.
        /// </summary>
        public static string GreetingCard {
            get {
                return ResourceManager.GetString("GreetingCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in Arabic.
        /// </summary>
        public static string InArabic {
            get {
                return ResourceManager.GetString("InArabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in English.
        /// </summary>
        public static string InEnglish {
            get {
                return ResourceManager.GetString("InEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Session, You will be redirected to login page.
        /// </summary>
        public static string InvalidSessionMessage {
            get {
                return ResourceManager.GetString("InvalidSessionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT Services Desk.
        /// </summary>
        public static string ITServicesDesk {
            get {
                return ResourceManager.GetString("ITServicesDesk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title.
        /// </summary>
        public static string JobTitle {
            get {
                return ResourceManager.GetString("JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please reopen the app to change the language.
        /// </summary>
        public static string LanguageChangedText {
            get {
                return ResourceManager.GetString("LanguageChangedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language saved.
        /// </summary>
        public static string LanguageSaved {
            get {
                return ResourceManager.GetString("LanguageSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Location.
        /// </summary>
        public static string LastLocation {
            get {
                return ResourceManager.GetString("LastLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Seen.
        /// </summary>
        public static string LastSeen {
            get {
                return ResourceManager.GetString("LastSeen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Late.
        /// </summary>
        public static string Late {
            get {
                return ResourceManager.GetString("Late", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoadingError.
        /// </summary>
        public static string LoadingError {
            get {
                return ResourceManager.GetString("LoadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        public static string Manager {
            get {
                return ResourceManager.GetString("Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meduim.
        /// </summary>
        public static string Meduim {
            get {
                return ResourceManager.GetString("Meduim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number.
        /// </summary>
        public static string MobileNumber {
            get {
                return ResourceManager.GetString("MobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY DELEGATIONS.
        /// </summary>
        public static string MyDelegationsCap {
            get {
                return ResourceManager.GetString("MyDelegationsCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Requests.
        /// </summary>
        public static string MyRequests {
            get {
                return ResourceManager.GetString("MyRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY REQUESTS.
        /// </summary>
        public static string MyRequestsCap {
            get {
                return ResourceManager.GetString("MyRequestsCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Sub Attendance.
        /// </summary>
        public static string MySubAttendance {
            get {
                return ResourceManager.GetString("MySubAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY SUB ATTENDANCE.
        /// </summary>
        public static string MySubAttendanceCap {
            get {
                return ResourceManager.GetString("MySubAttendanceCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Tasks.
        /// </summary>
        public static string MyTasks {
            get {
                return ResourceManager.GetString("MyTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY TASKS.
        /// </summary>
        public static string MyTasksCap {
            get {
                return ResourceManager.GetString("MyTasksCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW DELEGATION.
        /// </summary>
        public static string NewDelegationCap {
            get {
                return ResourceManager.GetString("NewDelegationCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Request.
        /// </summary>
        public static string NewRequest {
            get {
                return ResourceManager.GetString("NewRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW REQUEST.
        /// </summary>
        public static string NewRequestCap {
            get {
                return ResourceManager.GetString("NewRequestCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data found.
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Internet.
        /// </summary>
        public static string NoInternet {
            get {
                return ResourceManager.GetString("NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer Maintenance.
        /// </summary>
        public static string OfferMaintenance {
            get {
                return ResourceManager.GetString("OfferMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer Services.
        /// </summary>
        public static string OfferServices {
            get {
                return ResourceManager.GetString("OfferServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Location.
        /// </summary>
        public static string OfficeLocation {
            get {
                return ResourceManager.GetString("OfficeLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFFICE MAINTENANCE.
        /// </summary>
        public static string OfficeMaintenanceCap {
            get {
                return ResourceManager.GetString("OfficeMaintenanceCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Number.
        /// </summary>
        public static string OfficeNumber {
            get {
                return ResourceManager.GetString("OfficeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oracle Services.
        /// </summary>
        public static string OracleServices {
            get {
                return ResourceManager.GetString("OracleServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password and confirm password do not match.
        /// </summary>
        public static string PassAndConfirmPassAreNotEqual {
            get {
                return ResourceManager.GetString("PassAndConfirmPassAreNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and confirm password should be at least 8 charachters.
        /// </summary>
        public static string PassLessThan8CharsMessage {
            get {
                return ResourceManager.GetString("PassLessThan8CharsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason should not contain any special characters.
        /// </summary>
        public static string PassReasonShouldnotContainSpecialCharchters {
            get {
                return ResourceManager.GetString("PassReasonShouldnotContainSpecialCharchters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password should not contain special charachters.
        /// </summary>
        public static string PassShouldnotContainSpecialChars {
            get {
                return ResourceManager.GetString("PassShouldnotContainSpecialChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal.
        /// </summary>
        public static string Personal {
            get {
                return ResourceManager.GetString("Personal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter missing fields.
        /// </summary>
        public static string PleaseEnterMissingFields {
            get {
                return ResourceManager.GetString("PleaseEnterMissingFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter new password and confirm password.
        /// </summary>
        public static string PleaseEnterPassAndConfirmPass {
            get {
                return ResourceManager.GetString("PleaseEnterPassAndConfirmPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter reason.
        /// </summary>
        public static string PleaseEnterReason {
            get {
                return ResourceManager.GetString("PleaseEnterReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter User Name.
        /// </summary>
        public static string PleaseenterUserName {
            get {
                return ResourceManager.GetString("PleaseenterUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter User Name and Password.
        /// </summary>
        public static string PleaseenterUserNameandPassword {
            get {
                return ResourceManager.GetString("PleaseenterUserNameandPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to select equipments.
        /// </summary>
        public static string PressToSelectEquipments {
            get {
                return ResourceManager.GetString("PressToSelectEquipments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string PriorityMedium {
            get {
                return ResourceManager.GetString("PriorityMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string PriorityNormal {
            get {
                return ResourceManager.GetString("PriorityNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urgent.
        /// </summary>
        public static string PriorityUrgent {
            get {
                return ResourceManager.GetString("PriorityUrgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        public static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason Type.
        /// </summary>
        public static string ReasonType {
            get {
                return ResourceManager.GetString("ReasonType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining.
        /// </summary>
        public static string Remaining {
            get {
                return ResourceManager.GetString("Remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Delegation.
        /// </summary>
        public static string RemoveDelegation {
            get {
                return ResourceManager.GetString("RemoveDelegation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request an Accouncement.
        /// </summary>
        public static string RequestAnnouncement {
            get {
                return ResourceManager.GetString("RequestAnnouncement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string RequestDate {
            get {
                return ResourceManager.GetString("RequestDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Date/Time.
        /// </summary>
        public static string RequestDateTime {
            get {
                return ResourceManager.GetString("RequestDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Details.
        /// </summary>
        public static string RequestDetails {
            get {
                return ResourceManager.GetString("RequestDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REQUEST DETAILS.
        /// </summary>
        public static string RequestDetailsCap {
            get {
                return ResourceManager.GetString("RequestDetailsCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request a Driver.
        /// </summary>
        public static string RequestDriver {
            get {
                return ResourceManager.GetString("RequestDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request an Office Maintenance.
        /// </summary>
        public static string RequestOfficeMaintenance {
            get {
                return ResourceManager.GetString("RequestOfficeMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request an Office Service.
        /// </summary>
        public static string RequestOfficeService {
            get {
                return ResourceManager.GetString("RequestOfficeService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Status.
        /// </summary>
        public static string RequestStatus {
            get {
                return ResourceManager.GetString("RequestStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string RequestTitle {
            get {
                return ResourceManager.GetString("RequestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Type.
        /// </summary>
        public static string RequestType {
            get {
                return ResourceManager.GetString("RequestType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Research Request.
        /// </summary>
        public static string ResearchRequest {
            get {
                return ResourceManager.GetString("ResearchRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Date Should be Greater than Departure Date.
        /// </summary>
        public static string ReturnDateShouldBeGreaterThanDepartureDate {
            get {
                return ResourceManager.GetString("ReturnDateShouldBeGreaterThanDepartureDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Today.
        /// </summary>
        public static string ReturnToday {
            get {
                return ResourceManager.GetString("ReturnToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room.
        /// </summary>
        public static string Room {
            get {
                return ResourceManager.GetString("Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule Status.
        /// </summary>
        public static string RuleStatus {
            get {
                return ResourceManager.GetString("RuleStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Card.
        /// </summary>
        public static string SaveCard {
            get {
                return ResourceManager.GetString("SaveCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search all contacts.
        /// </summary>
        public static string SearchAllContacts {
            get {
                return ResourceManager.GetString("SearchAllContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select office location first..
        /// </summary>
        public static string SelectOfficleLocationFirst {
            get {
                return ResourceManager.GetString("SelectOfficleLocationFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT SERVICE.
        /// </summary>
        public static string SelectServiceCap {
            get {
                return ResourceManager.GetString("SelectServiceCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Attachemnt.
        /// </summary>
        public static string ServcieDesk_AddAttachment {
            get {
                return ResourceManager.GetString("ServcieDesk_AddAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ServcieDesk_Description {
            get {
                return ResourceManager.GetString("ServcieDesk_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Category.
        /// </summary>
        public static string ServcieDesk_SelectCategory {
            get {
                return ResourceManager.GetString("ServcieDesk_SelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Name.
        /// </summary>
        public static string ServcieDesk_SelectName {
            get {
                return ResourceManager.GetString("ServcieDesk_SelectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string ServcieDesk_Title {
            get {
                return ResourceManager.GetString("ServcieDesk_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Behalf of.
        /// </summary>
        public static string ServiceDesk_BehalfOf {
            get {
                return ResourceManager.GetString("ServiceDesk_BehalfOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Name.
        /// </summary>
        public static string ServiceDesk_EmployeeName {
            get {
                return ResourceManager.GetString("ServiceDesk_EmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Cannot Exceed 2 MB.
        /// </summary>
        public static string ServiceDesk_FileCannotExceed {
            get {
                return ResourceManager.GetString("ServiceDesk_FileCannotExceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT Service Desk.
        /// </summary>
        public static string ServiceDesk_HomePagePageTitle {
            get {
                return ResourceManager.GetString("ServiceDesk_HomePagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log An Incident.
        /// </summary>
        public static string ServiceDesk_LogAnIncident {
            get {
                return ResourceManager.GetString("ServiceDesk_LogAnIncident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Cases.
        /// </summary>
        public static string ServiceDesk_MyCases {
            get {
                return ResourceManager.GetString("ServiceDesk_MyCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Requests.
        /// </summary>
        public static string ServiceDesk_MyRequests {
            get {
                return ResourceManager.GetString("ServiceDesk_MyRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request for IT Service.
        /// </summary>
        public static string ServiceDesk_RequestITService {
            get {
                return ResourceManager.GetString("ServiceDesk_RequestITService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string ServiceDesk_Search {
            get {
                return ResourceManager.GetString("ServiceDesk_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Details.
        /// </summary>
        public static string ServiceDetails {
            get {
                return ResourceManager.GetString("ServiceDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS.
        /// </summary>
        public static string SettingsCap {
            get {
                return ResourceManager.GetString("SettingsCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Password.
        /// </summary>
        public static string ShowPassword {
            get {
                return ResourceManager.GetString("ShowPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something error happened.
        /// </summary>
        public static string SomethingErrorHappened {
            get {
                return ResourceManager.GetString("SomethingErrorHappened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Location.
        /// </summary>
        public static string SourceLocation {
            get {
                return ResourceManager.GetString("SourceLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify equipments..
        /// </summary>
        public static string SpecifyEquipments {
            get {
                return ResourceManager.GetString("SpecifyEquipments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify which room..
        /// </summary>
        public static string SpecifyRoom {
            get {
                return ResourceManager.GetString("SpecifyRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub-ordinate.
        /// </summary>
        public static string SubOrdinate {
            get {
                return ResourceManager.GetString("SubOrdinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task details.
        /// </summary>
        public static string TaskDetails {
            get {
                return ResourceManager.GetString("TaskDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TASK DETAILS.
        /// </summary>
        public static string TaskDetailsCap {
            get {
                return ResourceManager.GetString("TaskDetailsCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text limit.
        /// </summary>
        public static string TextLimit {
            get {
                return ResourceManager.GetString("TextLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADAA Time Sheet.
        /// </summary>
        public static string TimeSheet_ADAATimeSheet {
            get {
                return ResourceManager.GetString("TimeSheet_ADAATimeSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Task.
        /// </summary>
        public static string TimeSheet_AddNewTask {
            get {
                return ResourceManager.GetString("TimeSheet_AddNewTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigment Date.
        /// </summary>
        public static string TimeSheet_AssigmentDate {
            get {
                return ResourceManager.GetString("TimeSheet_AssigmentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigment Name / Task.
        /// </summary>
        public static string TimeSheet_AssigmentName {
            get {
                return ResourceManager.GetString("TimeSheet_AssigmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigment Name.
        /// </summary>
        public static string TimeSheet_AssigName {
            get {
                return ResourceManager.GetString("TimeSheet_AssigName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string TimeSheet_Comment {
            get {
                return ResourceManager.GetString("TimeSheet_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string TimeSheet_Duration {
            get {
                return ResourceManager.GetString("TimeSheet_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndDate.
        /// </summary>
        public static string TimeSheet_EndDate {
            get {
                return ResourceManager.GetString("TimeSheet_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Choose Assigment.
        /// </summary>
        public static string TimeSheet_EnterAssigmnet {
            get {
                return ResourceManager.GetString("TimeSheet_EnterAssigmnet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Choose Comment.
        /// </summary>
        public static string TimeSheet_EnterComment {
            get {
                return ResourceManager.GetString("TimeSheet_EnterComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Duration.
        /// </summary>
        public static string TimeSheet_EnterDuration {
            get {
                return ResourceManager.GetString("TimeSheet_EnterDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Choose Task.
        /// </summary>
        public static string TimeSheet_EnterTask {
            get {
                return ResourceManager.GetString("TimeSheet_EnterTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Happened.
        /// </summary>
        public static string TimeSheet_ErrorHappened {
            get {
                return ResourceManager.GetString("TimeSheet_ErrorHappened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in Hours.
        /// </summary>
        public static string TimeSheet_LoginHours {
            get {
                return ResourceManager.GetString("TimeSheet_LoginHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Assignments.
        /// </summary>
        public static string TimeSheet_MyAssignment {
            get {
                return ResourceManager.GetString("TimeSheet_MyAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Pending Tasks.
        /// </summary>
        public static string TimeSheet_MyPendingTasks {
            get {
                return ResourceManager.GetString("TimeSheet_MyPendingTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Timesheet.
        /// </summary>
        public static string TimeSheet_MyTimeSheet {
            get {
                return ResourceManager.GetString("TimeSheet_MyTimeSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Task.
        /// </summary>
        public static string TimeSheet_OpenTask {
            get {
                return ResourceManager.GetString("TimeSheet_OpenTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Number.
        /// </summary>
        public static string TimeSheet_ReferenceName {
            get {
                return ResourceManager.GetString("TimeSheet_ReferenceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        public static string TimeSheet_Refrence {
            get {
                return ResourceManager.GetString("TimeSheet_Refrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining Hours.
        /// </summary>
        public static string TimeSheet_RemainingHours {
            get {
                return ResourceManager.GetString("TimeSheet_RemainingHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Task.
        /// </summary>
        public static string TimeSheet_RemoveTask {
            get {
                return ResourceManager.GetString("TimeSheet_RemoveTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Assigment.
        /// </summary>
        public static string TimeSheet_SelectAssigmnet {
            get {
                return ResourceManager.GetString("TimeSheet_SelectAssigmnet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Duration.
        /// </summary>
        public static string TimeSheet_SelectDuration {
            get {
                return ResourceManager.GetString("TimeSheet_SelectDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Task.
        /// </summary>
        public static string TimeSheet_SelectTask {
            get {
                return ResourceManager.GetString("TimeSheet_SelectTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string TimeSheet_StartDate {
            get {
                return ResourceManager.GetString("TimeSheet_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string TimeSheet_Status {
            get {
                return ResourceManager.GetString("TimeSheet_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Date.
        /// </summary>
        public static string TimeSheet_TaskDate {
            get {
                return ResourceManager.GetString("TimeSheet_TaskDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Name.
        /// </summary>
        public static string TimeSheet_TaskName {
            get {
                return ResourceManager.GetString("TimeSheet_TaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Todays Task.
        /// </summary>
        public static string TimeSheet_ViewTodaysTask {
            get {
                return ResourceManager.GetString("TimeSheet_ViewTodaysTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Equipment.
        /// </summary>
        public static string TypeOfEquipment {
            get {
                return ResourceManager.GetString("TypeOfEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlocking account request was unsuccessful.
        /// </summary>
        public static string UnlockAccountError {
            get {
                return ResourceManager.GetString("UnlockAccountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock my laptop account.
        /// </summary>
        public static string UnlockLaptopAccount {
            get {
                return ResourceManager.GetString("UnlockLaptopAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnLock My Account.
        /// </summary>
        public static string UnLockMyAccount {
            get {
                return ResourceManager.GetString("UnLockMyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urgent.
        /// </summary>
        public static string Urgent {
            get {
                return ResourceManager.GetString("Urgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Account Services.
        /// </summary>
        public static string UserAccountServices {
            get {
                return ResourceManager.GetString("UserAccountServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome,.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work.
        /// </summary>
        public static string Work {
            get {
                return ResourceManager.GetString("Work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong username or password.
        /// </summary>
        public static string WrongUsernameOrPassword {
            get {
                return ResourceManager.GetString("WrongUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not Delegate yourself.
        /// </summary>
        public static string YouCantDelegateYourselfMessage {
            get {
                return ResourceManager.GetString("YouCantDelegateYourselfMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no subordinates.
        /// </summary>
        public static string YouHaveNoSubordinates {
            get {
                return ResourceManager.GetString("YouHaveNoSubordinates", resourceCulture);
            }
        }
    }
}
