// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace AdaaMobile {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("AdaaMobile.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string InArabic {
            get {
                return ResourceManager.GetString("InArabic", resourceCulture);
            }
        }
        
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        public static string OfficeNumber {
            get {
                return ResourceManager.GetString("OfficeNumber", resourceCulture);
            }
        }
        
        public static string EmployeeID {
            get {
                return ResourceManager.GetString("EmployeeID", resourceCulture);
            }
        }
        
        public static string AnnouncementCap {
            get {
                return ResourceManager.GetString("AnnouncementCap", resourceCulture);
            }
        }
        
        public static string SelectServiceCap {
            get {
                return ResourceManager.GetString("SelectServiceCap", resourceCulture);
            }
        }
        
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        public static string AttendanceTab {
            get {
                return ResourceManager.GetString("AttendanceTab", resourceCulture);
            }
        }
        
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        public static string AdaaTimesheet {
            get {
                return ResourceManager.GetString("AdaaTimesheet", resourceCulture);
            }
        }
        
        public static string JobTitle {
            get {
                return ResourceManager.GetString("JobTitle", resourceCulture);
            }
        }
        
        public static string MyRequests {
            get {
                return ResourceManager.GetString("MyRequests", resourceCulture);
            }
        }
        
        public static string FirstSeen {
            get {
                return ResourceManager.GetString("FirstSeen", resourceCulture);
            }
        }
        
        public static string Certificate {
            get {
                return ResourceManager.GetString("Certificate", resourceCulture);
            }
        }
        
        public static string Attendance {
            get {
                return ResourceManager.GetString("Attendance", resourceCulture);
            }
        }
        
        public static string ReasonType {
            get {
                return ResourceManager.GetString("ReasonType", resourceCulture);
            }
        }
        
        public static string CertificateNameInArabic {
            get {
                return ResourceManager.GetString("CertificateNameInArabic", resourceCulture);
            }
        }
        
        public static string ExpectedReturnTime {
            get {
                return ResourceManager.GetString("ExpectedReturnTime", resourceCulture);
            }
        }
        
        public static string TaskDetailsCap {
            get {
                return ResourceManager.GetString("TaskDetailsCap", resourceCulture);
            }
        }
        
        public static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        public static string RuleStatus {
            get {
                return ResourceManager.GetString("RuleStatus", resourceCulture);
            }
        }
        
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        public static string MySubAttendanceCap {
            get {
                return ResourceManager.GetString("MySubAttendanceCap", resourceCulture);
            }
        }
        
        public static string Arabic {
            get {
                return ResourceManager.GetString("Arabic", resourceCulture);
            }
        }
        
        public static string OfferServices {
            get {
                return ResourceManager.GetString("OfferServices", resourceCulture);
            }
        }
        
        public static string NewRequestCap {
            get {
                return ResourceManager.GetString("NewRequestCap", resourceCulture);
            }
        }
        
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        public static string DelegationDetailsCap {
            get {
                return ResourceManager.GetString("DelegationDetailsCap", resourceCulture);
            }
        }
        
        public static string RequestDetailsCap {
            get {
                return ResourceManager.GetString("RequestDetailsCap", resourceCulture);
            }
        }
        
        public static string InEnglish {
            get {
                return ResourceManager.GetString("InEnglish", resourceCulture);
            }
        }
        
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        public static string DriverRequest {
            get {
                return ResourceManager.GetString("DriverRequest", resourceCulture);
            }
        }
        
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        public static string Delegation {
            get {
                return ResourceManager.GetString("Delegation", resourceCulture);
            }
        }
        
        public static string PriorityNormal {
            get {
                return ResourceManager.GetString("PriorityNormal", resourceCulture);
            }
        }
        
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        public static string UnLockMyAccount {
            get {
                return ResourceManager.GetString("UnLockMyAccount", resourceCulture);
            }
        }
        
        public static string DirectoryCap {
            get {
                return ResourceManager.GetString("DirectoryCap", resourceCulture);
            }
        }
        
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        public static string ForgetPassword {
            get {
                return ResourceManager.GetString("ForgetPassword", resourceCulture);
            }
        }
        
        public static string MyTasksCap {
            get {
                return ResourceManager.GetString("MyTasksCap", resourceCulture);
            }
        }
        
        public static string AdditionalComments {
            get {
                return ResourceManager.GetString("AdditionalComments", resourceCulture);
            }
        }
        
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        public static string MyTasks {
            get {
                return ResourceManager.GetString("MyTasks", resourceCulture);
            }
        }
        
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        public static string Work {
            get {
                return ResourceManager.GetString("Work", resourceCulture);
            }
        }
        
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        public static string LastSeen {
            get {
                return ResourceManager.GetString("LastSeen", resourceCulture);
            }
        }
        
        public static string Directory {
            get {
                return ResourceManager.GetString("Directory", resourceCulture);
            }
        }
        
        public static string Announcement {
            get {
                return ResourceManager.GetString("Announcement", resourceCulture);
            }
        }
        
        public static string MyDelegationsCap {
            get {
                return ResourceManager.GetString("MyDelegationsCap", resourceCulture);
            }
        }
        
        public static string GreetingCard {
            get {
                return ResourceManager.GetString("GreetingCard", resourceCulture);
            }
        }
        
        public static string ReturnToday {
            get {
                return ResourceManager.GetString("ReturnToday", resourceCulture);
            }
        }
        
        public static string DepratureTime {
            get {
                return ResourceManager.GetString("DepratureTime", resourceCulture);
            }
        }
        
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        public static string MyRequestsCap {
            get {
                return ResourceManager.GetString("MyRequestsCap", resourceCulture);
            }
        }
        
        public static string NewDelegationCap {
            get {
                return ResourceManager.GetString("NewDelegationCap", resourceCulture);
            }
        }
        
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        public static string OfferMaintenance {
            get {
                return ResourceManager.GetString("OfferMaintenance", resourceCulture);
            }
        }
        
        public static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        public static string Exceptions {
            get {
                return ResourceManager.GetString("Exceptions", resourceCulture);
            }
        }
        
        public static string DayPass {
            get {
                return ResourceManager.GetString("DayPass", resourceCulture);
            }
        }
        
        public static string MobileNumber {
            get {
                return ResourceManager.GetString("MobileNumber", resourceCulture);
            }
        }
        
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        public static string AnnouncementType {
            get {
                return ResourceManager.GetString("AnnouncementType", resourceCulture);
            }
        }
        
        public static string SettingsCap {
            get {
                return ResourceManager.GetString("SettingsCap", resourceCulture);
            }
        }
        
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        public static string RequestStatus {
            get {
                return ResourceManager.GetString("RequestStatus", resourceCulture);
            }
        }
        
        public static string EmptyPlaceHolder {
            get {
                return ResourceManager.GetString("EmptyPlaceHolder", resourceCulture);
            }
        }
        
        public static string DelegateName {
            get {
                return ResourceManager.GetString("DelegateName", resourceCulture);
            }
        }
        
        public static string FlowDirection {
            get {
                return ResourceManager.GetString("FlowDirection", resourceCulture);
            }
        }
        
        public static string AdditionalComment {
            get {
                return ResourceManager.GetString("AdditionalComment", resourceCulture);
            }
        }
        
        public static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        public static string CertificateNameInEnglish {
            get {
                return ResourceManager.GetString("CertificateNameInEnglish", resourceCulture);
            }
        }
        
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        public static string RequestDetails {
            get {
                return ResourceManager.GetString("RequestDetails", resourceCulture);
            }
        }
        
        public static string BuisnessCard {
            get {
                return ResourceManager.GetString("BuisnessCard", resourceCulture);
            }
        }
        
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        public static string SubOrdinate {
            get {
                return ResourceManager.GetString("SubOrdinate", resourceCulture);
            }
        }
        
        public static string ResearchRequest {
            get {
                return ResourceManager.GetString("ResearchRequest", resourceCulture);
            }
        }
    }
}
